# VAE compression for bounded gLV model with data generated by CDS
from VAE_CDS import *
import sys
import time as timer
import pickle

n_target=int(sys.argv[1])

trial=int(sys.argv[2])

N_EBD = [1, 2, 3, 5, 6, 8, 10, 12, 15, 20, 25, 30, 40, 50]

X_train,X_test = get_data(n_target)

t0=timer.perf_counter()
TRAIN_LOSS={}
TEST_LOSS={}

print("training started")
for n_embedding in N_EBD:
    train_loss, test_loss = run(n_target,n_embedding,X_train,X_test,trial)
    TRAIN_LOSS[n_embedding]=train_loss
    TEST_LOSS[n_embedding]=test_loss
loss_data = [TRAIN_LOSS,TEST_LOSS]
filename = f"./vae_models/bgLV_CDS/I1/CDS_T{n_target}_trial{trial}_traindoc.pkl"

with open(filename, 'wb') as f:
    pickle.dump(loss_data, f, protocol=pickle.HIGHEST_PROTOCOL)
train_time=timer.perf_counter()-t0
print("training finished, time used: %i s"%train_time)